SC_PROJECT = test
SC_BOARD = SC_F1_DISCOVERY
SC_DEFINES = -DHAL_USE_USB=FALSE -DHAL_USE_SERIAL_USB=FALSE -DHAL_USE_RTC=FALSE

# Disable ChibiOS features not used currently by Snowcap projects
SC_DEFINES += -DCH_USE_CONDVARS=FALSE -DCH_USE_EVENTS=FALSE -DCH_USE_MESSAGES=FALSE -DCH_USE_MEMCORE=FALSE -DCH_USE_HEAP=FALSE -DCH_USE_MEMPOOLS=FALSE -DCH_USE_DYNAMIC=FALSE

# Decrease the event loop thread's work area
SC_DEFINES += -DSC_EVENT_LOOP_THREAD_WA=512