SC_PROJECT = ahrs
SC_BOARD = SC_SNOWCAP_STM32F4_V1
SC_DEFINES = -DSC_USE_9DOF=TRUE -DSC_USE_AHRS=TRUE -DSC_ALLOW_GPL
# LSM9DS0:
#SC_DEFINES += -DSC_HAS_LSM9DS0 -DSC_WAR_ISSUE_1
# LSM9DS1:
SC_DEFINES += -DSC_HAS_LSM9DS1

# Include filters
SC_DEFINES += -DSC_USE_FILTER_ZERO_CALIBRATE -DSC_USE_FILTER_BROWN_LINEAR_EXPO

# Increase event thread WA
SC_DEFINES += -DSC_EVENT_LOOP_THREAD_WA=4096