SC_PROJECT = small
SC_BUILD_TYPE = release
SC_BOARD = SC_SNOWCAP_STM32F4_V1

# Disable ChibiOS HAL features
SC_DEFINES = -DHAL_USE_TM=FALSE -DHAL_USE_ADC=FALSE -DHAL_USE_CAN=FALSE -DHAL_USE_EXT=FALSE -DHAL_USE_GPT=FALSE -DHAL_USE_I2C=FALSE -DHAL_USE_ICU=FALSE -DHAL_USE_MAC=FALSE -DHAL_USE_MMC_SPI=FALSE -DHAL_USE_PWM=FALSE -DHAL_USE_RTC=FALSE -DHAL_USE_SDC=FALSE -DHAL_USE_SERIAL=FALSE -DHAL_USE_SERIAL_USB=FALSE -DHAL_USE_SPI=FALSE -DHAL_USE_UART=FALSE -DHAL_USE_USB=FALSE

# Set small queue etc. sizes
SC_DEFINES += -DPORT_INT_REQUIRED_STACK=32 -DEVENT_MB_SIZE=8 -DSC_BLOB_MAX_SIZE=8 -DSC_CMD_MAX_RECV_BUF_LEN=0

# Disable Chibios debugging, save  ~1k RAM.
# Disabled for release builds by default
#SC_DEFINES += -DCH_DBG_SYSTEM_STATE_CHECK=FALSE -DCH_DBG_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_TRACE=FALSE -DCH_DBG_ENABLE_STACK_CHECK=FALSE -DCH_DBG_FILL_THREADS=FALSE -DCH_DBG_THREADS_PROFILING=FALSE -DCH_DBG_STATISTICS=FALSE

# Make ChibiOS select size optimised implementation over speed optimisation, when choices exist.
# Increases size??
#SC_DEFINES += -DCH_OPTIMIZE_SPEED=FALSE


# Disable idle thread. Main thread must be running at idle priority and can't use sleep.
# Saves ~180 bytes of RAM
#SC_DEFINES += -DCH_NO_IDLE_THREAD=TRUE

# Disable ChibiOS features not used currently by Snowcap projects
SC_DEFINES += -DCH_USE_REGISTRY=FALSE -DCH_USE_CONDVARS=FALSE -DCH_USE_EVENTS=FALSE -DCH_USE_MESSAGES=FALSE -DCH_USE_MEMCORE=FALSE -DCH_USE_HEAP=FALSE -DCH_USE_MEMPOOLS=FALSE -DCH_USE_DYNAMIC=FALSE
