SC_PROJECT = pleco
SC_BOARD = SC_F401_NUCLEO

SC_DEFINES = -DHAL_USE_CAN=FALSE -DHAL_USE_ICU=FALSE -DHAL_USE_MAC=FALSE -DHAL_USE_MMC_SPI=FALSE -DHAL_USE_RTC=FALSE -DHAL_USE_SERIAL_USB=FALSE -DHAL_USE_USB=FALSE
