SC_PROJECT = pleco
SC_BOARD = SC_F401_NUCLEO

SC_DEFINES = -DHAL_USE_CAN=FALSE -DHAL_USE_ICU=FALSE -DHAL_USE_MAC=FALSE -DHAL_USE_MMC_SPI=FALSE -DHAL_USE_RTC=FALSE -DHAL_USE_SERIAL_USB=FALSE -DHAL_USE_USB=FALSE

# Use APA102 LED strip
SC_DEFINES += -DSC_HAS_APA102=1

# DC motors on NOR requires 20 kHz PWM. Use 8 MHz clock. 8 MHz / 20 kHz = 400
SC_DEFINES += -DSC_PWM_CLOCK_PWMD2=8000000
SC_DEFINES += -DSC_PWM_DEFAULT_PERIOD_PWMD2=400
