SC_PROJECT = test
SC_BOARD = SC_L1_NUCLEO
SC_DEFINES = -DHAL_USE_TM=FALSE -DHAL_USE_ADC=FALSE -DHAL_USE_CAN=FALSE -DHAL_USE_GPT=FALSE -DHAL_USE_ICU=FALSE -DHAL_USE_MAC=FALSE -DHAL_USE_MMC_SPI=FALSE -DHAL_USE_PWM=FALSE -DHAL_USE_RTC=FALSE -DHAL_USE_SDC=FALSE -DHAL_USE_SERIAL=FALSE -DHAL_USE_SERIAL_USB=FALSE -DHAL_USE_SPI=FALSE -DHAL_USE_USB=FALSE

# STM32L152 has only 16bit timer
SC_DEFINES += -DCH_CFG_ST_RESOLUTION=16

# Decrease frequency from 10000 to 1000 for STM32L152
SC_DEFINES += -DCH_CFG_ST_FREQUENCY=1000

SC_DEFINES += -DSC_HAS_LSM9DS1 -DSC_USE_9DOF=TRUE
#SC_DEFINES += -DSC_HAS_MS5611
