SC_PROJECT = pleco
SC_BOARD = SC_F401_NUCLEO

SC_DEFINES = -DHAL_USE_CAN=FALSE -DHAL_USE_ICU=FALSE -DHAL_USE_MAC=FALSE -DHAL_USE_MMC_SPI=FALSE -DHAL_USE_RTC=FALSE -DHAL_USE_SERIAL_USB=FALSE -DHAL_USE_USB=FALSE

# Enable third PWM driver to get PWM 10 for the glow effect
SC_DEFINES += -DPWMDX3=PWMD2
SC_DEFINES += -DSC_PWM3_2_PORT=GPIOB
SC_DEFINES += -DSC_PWM3_2_PIN=3
SC_DEFINES += -DSC_PWM3_2_AF=1
