SC_PROJECT = tracker
SC_BOARD = RT_C2

# Disable ChibiOS HAL features
SC_DEFINES = -DHAL_USE_ADC=FALSE -DHAL_USE_CAN=FALSE -DHAL_USE_ICU=FALSE -DHAL_USE_MAC=FALSE -DHAL_USE_MMC_SPI=FALSE -DHAL_USE_PWM=FALSE
