SC_PROJECT = tracker
SC_BOARD = RT_C2

# Disable ChibiOS HAL features
SC_DEFINES = -DHAL_USE_ADC=FALSE -DHAL_USE_CAN=FALSE -DHAL_USE_ICU=FALSE -DHAL_USE_MAC=FALSE -DHAL_USE_MMC_SPI=FALSE -DHAL_USE_PWM=FALSE

# Enabled Snowcap features
SC_DEFINES += -DSC_USE_NMEA=TRUE -DSC_ALLOW_GPL -DSC_USE_SLRE -DSC_USE_GSM -DSC_USE_SHA1

# Enable float type support in ch*printf
SC_DEFINES += -DCHPRINTF_USE_FLOAT=TRUE

# Increase the size of maximum UART message
SC_DEFINES += -DUART_MAX_SEND_BUF_LEN=254

# Increase the number of USB serial send buffers
SC_DEFINES += -DSDU_MAX_SEND_BUFFERS=8