language: c

notifications:
  irc:
    channels:
      - "chat.freenode.net#snowcap"
    on_success: change
    use_notice: true
    skip_join: true

before_script:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded > /dev/null 2>&1
  - sudo apt-get update -q
  - sudo apt-get install gcc-arm-none-eabi

script: ./compile-all-test.sh
