language: c

notifications:
  irc:
    channels:
      - "chat.freenode.net#snowcap"
    on_success: change
    use_notice: true
    skip_join: true

branches:
  only:
    - master

addons:
  coverity_scan:
    project:
      name: "snowcap-electronics/control-board"
      description: "MCU firmware"
    notification_email: tuomas@kulve.fi
    build_command_prepend: cov-configure --comptype gcc --compiler arm-none-eabi-gcc --template
    build_command: ./compile-all-test.sh store
    branch_pattern: master

before_script:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded > /dev/null 2>&1
  - sudo apt-get update -q
  - sudo apt-get install gcc-arm-none-eabi
  - gem install travis-artifacts

script: ./compile-all-test.sh store
